### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Jol3l** [ichbinwhy/amongushun#1]
Elindítom a játékot és elindul a Unity hibakereső.
Megpróbáltam kiszedni a képeket és a text fileokat de a képek (shaderasset5) le voltak tiltva valamiért a kicsomagoláshoz. Viszont a Text megfelelően működött, Miután átmásoltam az alap Shaderasset0-ba.
Javasolnám a UABE-nek a mod maker funcióját!

**Comment by ichbinwhy** [comment]
Szia!

Elvileg gond nélkül kellett volna tudnod elindítani a játékot a magyarítás telepítése után is. Én akkor kaptam crash-t és Unity Hibakeresőt, amikor elavult magyarításverzióval próbáltam elindítani a játékot. Ezen kívül a magyarítás public verzióhoz készült, viszont Steamnél beállítható a public-beta. (Ha ezt a verziót public-betaval használnád, akkor ha kilépnél a játékból a főmenübe, nagy eséllyel crashelni fog a játék.)

Nézegettem már a UABE-nek a mod maker funkcióját, viszont nem tudtam megfejteni a működését a Usage.txt elolvasása után sem. Lehet én vagyok ehhez buta.:(

**Comment by Jol3l** [comment]
> Szia!
> 
> Elvileg gond nélkül kellett volna tudnod elindítani a játékot a magyarítás telepítése után is. Én akkor kaptam crash-t és Unity Hibakeresőt, amikor elavult magyarításverzióval próbáltam elindítani a játékot. Ezen kívül a magyarítás public verzióhoz készült, viszont Steamnél beállítható a public-beta. (Ha ezt a verziót public-betaval használnád, akkor ha kilépnél a játékból a főmenübe, nagy eséllyel crashelni fog a játék.)
> 
> Nézegettem már a UABE-nek a mod maker funkcióját, viszont nem tudtam megfejteni a működését a Usage.txt elolvasása után sem. Lehet én vagyok ehhez buta.:(

 Megfelelő verzióval és Public Beta-val is működőképes a text ha az UABE-t használod a betételéhez viszont a Shaderasset5-el nem lehet semmit sem kezdeni sajnos. Megpróbáltan Kicsomagolni őket de hibaüzeneteket kaptam csak, akármelyik Unity verzióval próbálkoztam. Szívesen megcsinálnám nektek és akár egy exe formában is indítható lenne a telepítés viszont ahhoz szükséges lenne a megfelelő textúra csomag mert a jelenlegit nem lehet kiszedni sehogysem.
