### ISSUE TITLE
Crash nálam is

### ISSUE THREAD

**Issue by OldFirehandMan** [ichbinwhy/amongushun#2]
Üdv!
Steamről frissen letöltött (12.11) játék alapból indul. 
Megcsináltam az átmásolást, nekem is Unity hibakeresővel leáll.
Mit csináltam rosszul?

**Comment by ichbinwhy** [comment]
Szia. A jelenlegi fentlévő verzió elavult. Nem sokára frissítem! Köszi, hogy szóltál!
